version: '3'
services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app  
    environment:
      - NODE_ENV=production
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend 